# Generated by Django 3.2 on 2023-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactquery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={'verbose_name_plural': 'Contact Queries'},
        ),
        migrations.AddField(
            model_name='contactquery',
            name='subject',
            field=models.CharField(default='Dummy Subject', max_length=254),
            preserve_default=False,
        ),
    ]
